### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by 4mig4** [zielmicha/go2nim#1]
Would it be possible to get a modicum of documention in the Readme.md ? 

I am trying to use this with nim 1.2.6 and it does not work after having installed the nimble `collections`

It seems lots of things have changed in collections from the version hash go2nim requires.

**Comment by zielmicha** [comment]
This project didn't get to a phase were it would work reliably enough to be useful, documentation would not help.

**Comment by 4mig4** [comment]
I see closing this issue then
